#pragma once

#include <windows.h>

/* Beacon output types */
#define CALLBACK_OUTPUT      0x0
#define CALLBACK_ERROR       0x0d
#define CALLBACK_OUTPUT_UTF8 0x20

/* Beacon data parser */
typedef struct {
    char* original;
    char* buffer;
    int length;
    int size;
} datap;

/* Beacon API */
DECLSPEC_IMPORT VOID   WINAPI BeaconDataParse(datap*, char*, int);
DECLSPEC_IMPORT CHAR*  WINAPI BeaconDataExtract(datap*, int*);
DECLSPEC_IMPORT INT    WINAPI BeaconDataLength(datap*);
DECLSPEC_IMPORT INT    WINAPI BeaconDataInt(datap*);
DECLSPEC_IMPORT SHORT  WINAPI BeaconDataShort(datap*);
DECLSPEC_IMPORT VOID   WINAPI BeaconPrintf(int, char*, ...);
DECLSPEC_IMPORT VOID   WINAPI BeaconOutput(int, char*, int);

/* MSVCRT */
DECLSPEC_IMPORT void* __cdecl MSVCRT$memset(void*, int, size_t);

/* KERNEL32 — Process & Thread */
DECLSPEC_IMPORT WINBASEAPI HANDLE WINAPI KERNEL32$CreateThread(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
DECLSPEC_IMPORT WINBASEAPI DWORD  WINAPI KERNEL32$GetCurrentProcessId(VOID);
DECLSPEC_IMPORT WINBASEAPI HANDLE WINAPI KERNEL32$GetCurrentProcess(VOID);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$TerminateProcess(HANDLE, UINT);
DECLSPEC_IMPORT WINBASEAPI DWORD  WINAPI KERNEL32$ResumeThread(HANDLE);
DECLSPEC_IMPORT WINBASEAPI DWORD  WINAPI KERNEL32$QueueUserAPC(PAPCFUNC, HANDLE, ULONG_PTR);

/* KERNEL32 — Synchronization */
DECLSPEC_IMPORT WINBASEAPI VOID   WINAPI KERNEL32$InitializeCriticalSection(LPCRITICAL_SECTION);
DECLSPEC_IMPORT WINBASEAPI VOID   WINAPI KERNEL32$DeleteCriticalSection(LPCRITICAL_SECTION);
DECLSPEC_IMPORT WINBASEAPI VOID   WINAPI KERNEL32$EnterCriticalSection(LPCRITICAL_SECTION);
DECLSPEC_IMPORT WINBASEAPI VOID   WINAPI KERNEL32$LeaveCriticalSection(LPCRITICAL_SECTION);
DECLSPEC_IMPORT WINBASEAPI LONG   WINAPI KERNEL32$InterlockedExchange(volatile LONG*, LONG);
DECLSPEC_IMPORT WINBASEAPI LONG   WINAPI KERNEL32$InterlockedCompareExchange(volatile LONG*, LONG, LONG);
DECLSPEC_IMPORT WINBASEAPI DWORD  WINAPI KERNEL32$WaitForMultipleObjects(DWORD, const HANDLE*, BOOL, DWORD);
DECLSPEC_IMPORT WINBASEAPI VOID   WINAPI KERNEL32$Sleep(DWORD);

/* KERNEL32 — Handle & Memory */
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$CloseHandle(HANDLE);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$DuplicateHandle(HANDLE, HANDLE, HANDLE, LPHANDLE, DWORD, BOOL, DWORD);
DECLSPEC_IMPORT WINBASEAPI LPVOID WINAPI KERNEL32$VirtualAllocEx(HANDLE, LPVOID, SIZE_T, DWORD, DWORD);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$VirtualFreeEx(HANDLE, LPVOID, SIZE_T, DWORD);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$VirtualProtectEx(HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$WriteProcessMemory(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T*);
DECLSPEC_IMPORT WINBASEAPI HLOCAL WINAPI KERNEL32$LocalFree(HLOCAL);

/* KERNEL32 — Heap */
DECLSPEC_IMPORT WINBASEAPI HANDLE WINAPI KERNEL32$GetProcessHeap(VOID);
DECLSPEC_IMPORT WINBASEAPI LPVOID WINAPI KERNEL32$HeapAlloc(HANDLE, DWORD, SIZE_T);
DECLSPEC_IMPORT WINBASEAPI BOOL   WINAPI KERNEL32$HeapFree(HANDLE, DWORD, LPVOID);

/* KERNEL32 — Module & System */
DECLSPEC_IMPORT WINBASEAPI HMODULE WINAPI KERNEL32$GetModuleHandleA(LPCSTR);
DECLSPEC_IMPORT WINBASEAPI FARPROC WINAPI KERNEL32$GetProcAddress(HMODULE, LPCSTR);
DECLSPEC_IMPORT WINBASEAPI DWORD   WINAPI KERNEL32$GetLastError(VOID);
DECLSPEC_IMPORT WINBASEAPI VOID    WINAPI KERNEL32$GetSystemInfo(LPSYSTEM_INFO);

/* ADVAPI32 — Token */
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$OpenProcessToken(HANDLE, DWORD, PHANDLE);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$GetTokenInformation(HANDLE, TOKEN_INFORMATION_CLASS, LPVOID, DWORD, PDWORD);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$AdjustTokenPrivileges(HANDLE, BOOL, PTOKEN_PRIVILEGES, DWORD, PTOKEN_PRIVILEGES, PDWORD);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$LookupPrivilegeValueW(LPCWSTR, LPCWSTR, PLUID);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$ConvertSidToStringSidW(PSID, LPWSTR*);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$ImpersonateLoggedOnUser(HANDLE);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$RevertToSelf(VOID);

/* ADVAPI32 — Process creation */
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$CreateProcessWithLogonW(LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPCWSTR, LPWSTR, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$CreateProcessAsUserW(HANDLE, LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI ADVAPI32$CreateProcessWithTokenW(HANDLE, DWORD, LPCWSTR, LPWSTR, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
